A, B, C = input().split()
TRIANGULO=float((float(A)*float(C))/2)
CIRCULO=3.14159*(float(C)**2)
TRAPEZIO=float(((float(A)+float(B))/2)*float(C))
QUADRADO=float(float(B)**2)
RETANGULO=float(float(A)*float(B))
print("TRIANGULO: %.3f" %TRIANGULO)
print("CIRCULO: %.3f" %CIRCULO)
print("TRAPEZIO: %.3f" %TRAPEZIO)
print("QUADRADO: %.3f" %QUADRADO)
print("RETANGULO: %.3f" %RETANGULO)
